"""empty message

Revision ID: 2a7c93017f31
Revises: 
Create Date: 2023-11-03 18:39:52.671752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a7c93017f31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_lanzamiento', sa.Date(), nullable=True),
    sa.Column('generacion', sa.String(length=50), nullable=True),
    sa.Column('consolas_vendidas', sa.Integer(), nullable=True),
    sa.Column('imagen', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('juego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_lanzamiento', sa.Date(), nullable=True),
    sa.Column('genero', sa.String(length=50), nullable=True),
    sa.Column('copias_vendidas', sa.Integer(), nullable=True),
    sa.Column('imagen', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('franquicia', sa.String(length=50), nullable=True),
    sa.Column('habilidades', sa.String(length=200), nullable=True),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('imagen', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personaje')
    op.drop_table('juego')
    op.drop_table('consola')
    # ### end Alembic commands ###
